insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Value 반팔 [20수]', 2, 'Y', 'Y', '1', '1', '/up/base_product/1/ValueS_Yellow_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Value 긴팔 [20수]', 2, 'Y', 'Y', '0', '0', '/up/base_product/20/ValueL_Black_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Gildan 76000 프리미엄 반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/2d8ddf0e6d7373b452c9f673857607f6.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Gildan 63000 소프트 반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/ebd16fb6405c8a2e494442e757d191bc.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('보카시 반팔 [20수]', 2, 'Y', 'Y', '0', '0', '/up/base_product/2/VH_Red_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Gildan 73800 이지케어 여성 폴로반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/9e4fbcf13936f6f1563adafe8a332641.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Gildan 73800 이지케어 폴로반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/00938fb9bccb0a6c89087c9a040d12fc.PNG');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Gildan 76000 프리미엄 여성 반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/34f78d9c24a5584cfc395dc437836f7e.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('나그랑 반팔 [20수]', 2, 'Y', 'Y', '0', '0', '/up/base_product/3/ValueB_Purple_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('나그랑 긴팔 [20수]', 2, 'Y', 'Y', '0', '1', '/up/base_product/15/ValueBL_Red_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 1301 반팔 [수입]', 2, 'Y', 'Y', '1', '1', '/up/base_product/4/AAAS_Cream_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 1701 슬림반팔 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/5/AAA1701S_Navy_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 1304 긴팔 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/19/AAAL_Blue_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA V넥 반팔 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/6/AAAV_White_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA  베이스볼 [수입]', 2, 'Y', 'Y', '0', '1', '/up/base_product/8d798dded79acdebf6169ed7cb546b1e.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Basic V넥 반팔', 2, 'Y', 'Y', '1', '0', '/up/base_product/3364dbc9e54fa944985c6f3107b2a5e4.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('아메리칸어페럴 베이스볼 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/17/AABB453_BWhite_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA  머슬티 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/28/AAAM_Black_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 탱크탑 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/29/AAA_Tang_White_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 링어 반팔 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/10/AAAR_BBlue_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('아메리칸어페럴 반팔 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/14/AA2001_Rasberry_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('PK 폴로 반팔 [20수]', 2, 'Y', 'Y', '1', '0', '/up/base_product/7/PKS_Wine_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('PK 폴로 긴팔 [20수]', 2, 'Y', 'Y', '0', '0', '/up/base_product/18/PKL_Hpink_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Basic 라운드넥 반팔', 2, 'Y', 'Y', '1', '0', '/up/base_product/1f81f66fe0454d38d9af6f0b227e8038.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('스판텍스 반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/12/KS306_Lgreen_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('쿨론 반팔', 2, 'Y', 'Y', '0', '0', '/up/base_product/13/KS301_Blue_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('특양면 맨투맨', 2, 'Y', 'Y', '0', '0', '/up/base_product/21/CM_Pink_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('특양면 후드', 2, 'Y', 'Y', '0', '1', '/up/base_product/28c30bd57ae2dedb1efcc994c3914bf0.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('특양면 집업후드', 2, 'Y', 'Y', '0', '1', '/up/base_product/9bbd5ee75bcd2871347300c8814800f4.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Basic 맨투맨 [기모]', 2, 'Y', 'Y', '0', '0', '/up/base_product/22/BM_Navy_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Basic 후드 [기모]', 2, 'Y', 'Y', '0', '0', '/up/base_product/23/BH_Chacol_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Basic 집업후드 [기모]', 2, 'Y', 'Y', '0', '0', '/up/base_product/27/BZ_Orange_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('SHAKA 맨투맨 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/25/Shaka_Chacol_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 후드 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/24/AAAH_Navy_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('AAA 집업후드 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/26/AAAZ_Red_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('키즈 Creeper', 2, 'Y', 'Y', '0', '0', '/up/base_product/33/KID_creeper_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('헤인즈 키즈 반팔', 2, 'Y', 'Y', '0', '0', '/up/base_product/35/HKS_Pink_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('아메리칸어페럴 키즈베이스볼 [수입]', 2, 'Y', 'Y', '0', '0', '/up/base_product/34/AABB053_WBlack_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Basic 아동 반팔', 2, 'Y', 'Y', '1', '0', '/up/base_product/4efb9dbd22eb995e477857c09995d24b.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Value 아동 반팔 [ 20수]', 2, 'Y', 'Y', '0', '0', '/up/base_product/31/ValueKS_Sora_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('Gildan 76000 프리미엄 키즈 반팔', 2, 'Y', 'Y', '1', '1', '/up/base_product/e89d0d1b994aea11dc2b92862e814fc9.PNG');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('캔버스 스쿨가방', 2, 'Y', 'Y', '0', '0', '/up/base_product/36/CSB_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('캔버스 토트가방', 2, 'Y', 'Y', '0', '0', '/up/base_product/37/CTB_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('머그컵', 2, 'Y', 'Y', '0', '1', '/up/base_product/38/Mug_F.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('앞치마', 2, 'Y', 'Y', '0', '0', '/up/base_product/11425c165963cb5c8b6183514bcf5532.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('매쉬캡', 2, 'Y', 'Y', '0', '0', '/up/base_product/40/MS_brown.png');
insert into product(product_name, hit_count, use_yn, display_yn, hot, best, file_name) values('스냅백', 2, 'Y', 'Y', '0', '0', '/up/base_product/9a06ef6d5fb3f499c2460d7d93b4f7bf.png');