insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ001', 'XS(85)', 1, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ002', 'S(90~95)', 2, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ003', 'M(100)', 3, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ004', 'L(105)', 4, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ005', 'XL(110)', 5, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ006', '2XL(120)', 6, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ007', 'S(85)', 7, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ008', 'M(90)', 8, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ009', 'L(95)', 9, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ010', 'XL(100)', 10, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ011', '2XL(105)', 11, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ012', '3XL(110)', 12, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ013', 'M(95)', 13, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ014', 'L(100)', 14, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ015', 'XL(105)', 15, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ016', '3~6개월', 16, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ017', '12~18개월', 17, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ018', '24개월(3호)', 18, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ019', '2~3살(5호)', 19, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ020', '4~5살(7호)', 20, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ021', '1T(1살)', 21, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ022', '2T(2살)', 22, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ023', '3T(12개월)', 23, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ024', '4T(3~4살)', 24, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ025', '14호(5-6세)', 25, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ026', '15호(7-8세)', 26, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ027', '16호(9-10세)', 27, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ028', '17호(11-12세)', 28, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ029', '18호(13-14세)', 29, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ030', 'Free', 30, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ031', '11oz', 31, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ032', 'XS(80)', 32, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ033', 'S(85)', 33, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ034', 'M(90)', 34, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ035', 'L(95)', 35, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ036', 'XL(100)', 36, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ037', '2XL(110)', 37, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ038', 'S(75)', 38, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ039', 'M(80)', 39, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ040', 'L(85)', 40, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ041', 'XL(90)', 41, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ042', 'XS(60)', 42, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ043', 'S(65)', 43, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ044', 'M(70)', 44, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ045', 'L(75)', 45, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ046', 'XL(85)', 46, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('SIZE', 'SZ047', '3XL(120)', 47, 'Y');




insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', '000000', '블랙   ', 1, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', '022954', '네이비 ', 2, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', '304dc2', '블루   ', 3, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', '8bdfff', '소라   ', 4, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', 'c3bfbe', '그레이 ', 5, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', 'd02933', '레드   ', 6, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', 'dc3c78', '핫핑크 ', 7, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', 'f8d6d5', '연핑크 ', 8, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', 'ffee49', '노랑   ', 9, 'Y');
insert into common_code(code_class, code_key, code_value, code_order, code_use_yn) values('COLOR', 'ffffff', '화이트 ', 10, 'Y');
